<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="IN-996XTN3" failures="1" tests="3" name="Test" time="54.569" errors="0" timestamp="2023-07-26T16:42:48 IST">
  <testcase classname="Automation_wbsite_test.EndToEndWholeTest" name="EndToEndTestRun" time="27.281"/>
  <testcase classname="Automation_wbsite_test.EndToEndWholeTest" name="EndToEndTestRun" time="24.158"/>
  <testcase classname="Automation_wbsite_test.ToFailTest" name="FailtestScenario" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [Automation Exercise!!] but found [Automation Exercise]">
      <![CDATA[java.lang.AssertionError: expected [Automation Exercise!!] but found [Automation Exercise]
at Automation_wbsite_test.ToFailTest.FailtestScenario(ToFailTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- FailtestScenario -->
  <testcase classname="TestBase.Base" name="@AfterSuite email" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite email -->
  <testcase classname="TestBase.Base" name="@BeforeSuite initialization" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initialization -->
</testsuite> <!-- Test -->
